### ISSUE TITLE
Disk space used by cache growing too large

### ISSUE THREAD

**Issue by JeffPyeBrook** [futtta/autoptimize#10]
Ran into an issue on a couple of sites where the javascript cache is growing many gigabytes too large.  Looking at the cached files there are a couple things I noticed.  

Many of the files have identical contents.  Is there any way we can have the optimizer use the file contents to create the file name hash?  This would stop the data duplication.

If it is the case we need to know the filename where the collected and minified javascript is being stored very early in the page generation process perhaps we could create the file name as we are doing now but use a link to connect it to the file data?

I also noticed the option **autoptimize_cache_nogzip** in the code but couldn't find documentation on how the zip functionality might be used to save disk space?

**Comment by futtta** [comment]
Well, filename is autoptimize_\<md5 hash of the file-contents\>.js (see [classes/autoptimizeScripts.php](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeScripts.php#L177)), so that means there have to be (minor) differences between those files. This is typically caused by plugins inserting small pieces of page- (or request-)specific inline code. As inline code is aggregated by default, this has as a consequence that a huge amount of files are being created. 

There are 2 solutions for this problem:
1. finding the the offending JS-code and exclude that from being aggregated ([see FAQ](https://wordpress.org/plugins/autoptimize/faq/))
2. disabling aggregation of inline JS as a whole, which can be done using the API as seen in [autoptimize_helper.php_example](https://github.com/futtta/autoptimize/blob/master/autoptimize_helper.php_example#L112)

For AO 2.0 I will most probably make "aggregate inline JS" (and CSS) an option in the settings-page (which will be off by default, to avoid people running into this particular issue).

Concerning autoptimize_cache_nogzip is the option used to store the setting if autoptimize JS/ CSS is to be delivered statically (true) or dynamically (false), this logic is in classes/autoptimizeCache.php.

Hope this clarifies :-)

frank

**Comment by JeffPyeBrook** [comment]
thanks @futtta, and sorry for the noise.

i'll try to find out why my compare of the files shows them as identical, but obviously the live code is not.   It's got to be something simple

**Comment by JeffPyeBrook** [comment]
> For AO 2.0 I will most probably make "aggregate inline JS" (and CSS) an option in the 
> settings-page (which will be off by default, to avoid people running into this particular issue).

@futta I have tweaked some of the plugins I use to put a well known class attribute on scripts that I don't wan't moved out of the code.  Most of these tend to be the CDATA only scripts that get created as a result of wp_localize_script.

@futta 

If you are thinking about providing some additional options around what to localize, perhaps a "don't localize CDATA only scripts "  option would be useful.  These scripts don't seem to impact page speed scores, not sure about if the browsers are tagging these as blocking or not?

**Comment by futtta** [comment]
hiya @JeffPyeBrook;

Generally speaking CDATA-blocks are actually [leftovers from the XHTML-days](http://en.wikipedia.org/wiki/CDATA#Use_of_CDATA_in_program_output) to identify parts of the XML-tree that was to be excluded from XML-parsing. As such any inline JS could be blocking or non-blocking, depending on what the JS is doing. Just setting some variables would be non-blocking, but doing some heavy lifting (and e.g. connecting to 3rd parties) would clearly be blocking, no matter if the JS was enclosed in CDATA-markers or not.

Now specifically for WP-scripts; it indeed seems that WP core inserts CDATA-markers when doing wp_localize_script (as [per print_extra_script() in wp-includes/class.wp-scripts.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/class.wp-scripts.php#L77), which mentions CDATA is not needed, so it might get dropped anyhow).

Conclusion: I'm not sure it's a good idea to to rely on that in AO-core But one could simply add "CDATA" to AO's JS exclusion-list if one wanted to, no?

**Comment by JeffPyeBrook** [comment]
@futtta Yes, I also experimented with adding the CDATA to the exclusion list and everything that you would expect to was skipped, but ended up adding the class attribute to the plugins to get better control.  It was necessary because I wanted to ensure some scripts with CDATA were parsed prior to other javascript. Specifically, AdWords and Google Analytics scripts.
