### ISSUE TITLE
Option to use Transients API for cache storage

### ISSUE THREAD

**Issue by msigley** [futtta/autoptimize#12]
For those of us with more powerful hosting environments, it would be nice if their was an option to use the Wordpress Transients API instead of file caching. The Transients are stored in the server RAM if the site has some kind of caching setup.
http://codex.wordpress.org/Transients_API

**Comment by futtta** [comment]
Hmmm ... the problem is that Apache (or your webserver of choice) needs access to the cached files (if you look at the HTML source you'll see references to /wp-content/cache/autoptimize/js/autoptimize_xyz.js or css/autoptimize_xyz.js). When storing in transients you'd have to execute PHP (and bootstrap WP) to be able to access the transient, which would actually slow down the serving of the autoptimized JS/CSS?

Or do you have something else in mind?

frank

**Comment by msigley** [comment]
Frank,

Thanks for the response. I reviewed the source and I agree with your assessment for accessing the cached files.

Do you think we could use the transients to help speed up the generation of the cached files by eliminating some of the other intermediate temp files in the cache folder.

**Comment by futtta** [comment]
well ... what intermediate temp files are you referring to?

**Comment by msigley** [comment]
The .img and .txt files that are created in the wp-content/cache/autoptimize directory.

**Comment by futtta** [comment]
the .txt aren't tmp files I'm afraid, but are -historically- used to serve data:uri images to old versions of IE.

the .img-files are indeed temp files (also used for data-uri'ed images) and moving them to a transient could be done, but to be honest I don't see a huge advantage there warranting such a change (given that data-uri's are off by default, only apply to small background-images resulting in a very limited number of files in cache).
