### ISSUE TITLE
@Import Flagged in GTMetrix

### ISSUE THREAD

**Issue by norwayluta** [futtta/autoptimize#125]
The following external stylesheets were included in https://www.bothellhouselistings.com/wp-content/cache/autoptimize/autoptimize_66a7a6b45d11560ef9d72fdce66dafe0.php using @import.

Is this something that can be fixed?

Also Autoptimize is loading slowing and has x-proxy-cache MISS.
I recently changed from http to https. I'm not sure if that has anything to do with it, but any suggestions are welcomed. Thank you!

**Comment by futtta** [comment]
the imports mentioned originate from your theme's CSS @norwayluta cfr. https://www.bothellhouselistings.com/wp-content/themes/squared/css/main_teal.css

x-proxy-cache is because you have a caching proxy/ cdn which has to pull the files upon first hit, which also explains the slowness.

if you have follow-up questions, do post them in [the wordpress support forum](https://wordpress.org/support/plugin/autoptimize) please, GitHub tickets are for coding issues with AO rather then usage questions.

have a nice day :-)
frank
