### ISSUE TITLE
Background image in CSS not shortpixeled

### ISSUE THREAD

**Issue by christophcemper** [futtta/autoptimize#167]
Would be great to have the background image used in the CSS also short-pixeled

**Comment by futtta** [comment]
that it should actually, cfr. e.g.
http://blog.futtta.be/wp-content/cache/autoptimize/css/autoptimize_b62e1a677af2091bd68aa8ec4aec22dc.css
.

this is subject to a number of conditions:
* only for autoptimized CSS
* image has to be on own domain
* has to be jpg/ gif/ png
* should not have .php in the URL

frank

**Comment by futtta** [comment]
I checked you CSS @christophcemper , you have:
* 35 background-images that are inlined in your CSS (which is good), so those are not shortpixelled
* 10 background-images that are shortpixeled
* 1 svg background-image, which cannot be optimized by shortpixel or similar services

So this looks OK to me really.

The problem though is that you'll still see the images being requested from your own site because shortpixel does not succeed in fetching the images, so can't optimize and hence redirects to the original URL as fallback. The reason is your basic authentication, which makes the site inaccessible to shortpixel as well. This also applies to your remark about the lazy-load gif by the way.
