### ISSUE TITLE
CSS file problems are still showing

### ISSUE THREAD

**Issue by SimoneMuc** [futtta/autoptimize#177]
Hey Frank, 

After installing your plugin Autoptimize (version 2.3.4) I checked my website (nutritionisthenewsmart.com) with google page speed. 

When the 2 boxes „Optimize Java Script“ + „Optimize CSS“ are checked the page speed for mobile is 68/100. 
These two files show up to be optimized:

https://nutritionisthenewsmart.com/wp-content/cache/autoptimize/css/autoptimize_a774d078809dbb19b24549948e04df7b.css

https://nutritionisthenewsmart.com/wp-content/uploads/fvm/out/header-b47b383f-1531297932.min.css

If only the „Optimize Java Script“ box is checked, the page speed is 78/100. That´s better but then there is still one file showing to be optimized:

https://nutritionisthenewsmart.com/wp-content/uploads/fvm/out/header-b47b383f-1531297932.min.css

Which settings do I need for the best optimization?

Sincerely, 

Simone

**Comment by futtta** [comment]
Hi @SimoneMuc 

The Github issues are acutally only for code problems (bugs), whereas "user support" is provided on [the dedicated WordPress support forum](https://wordpress.org/support/plugin/autoptimize) :-)

But before closing this issue a number of quick pointers;
1. you're using AO and Fast Velocity Minify. This might work, but we (both Raoul & I) advice against this as both plugins do the same; is it best (and safer) to choose one and disable the other.
2. for render blocking AO CSS files you should look into the "inline & defer" option, see the [AO FAQ](https://wordpress.org/plugins/autoptimize/#faq) for more info.
3. if you have a render-blocking JS-file, you could remove `js/jquery/jquery.js` from AO's JS optimization exclusions, but do test your site thoroughly because some theme's and plugins require jquery to be available early.

If you have any more questions, do head over to [the WordPress Autoptimize support forum](https://wordpress.org/support/plugin/autoptimize) and I'll be happy to continue the conversation there! :-)
