### ISSUE TITLE
Autoptimize 2.4.4 breaks web page

### ISSUE THREAD

**Issue by harshadpp** [futtta/autoptimize#229]
Hi,
   I used autoptimize plugin (Version 2.4.4).  But it breaks the one page.  When I disable 
"Optimize CSS Code" in plugin settings the page will working properly. It works perfectly in development 
server, but when i move to live server such a problem occured. Is there any additional requirement need in server side.

**Comment by futtta** [comment]
hey @harshadpp ; github issues are for code-level problems/ bugs/ improvements, please open a topic on https://wordpress.org/support/plugin/autoptimize/#new-post and make sure to add some relevant info like your site's URL and a screenshot of the broken page.

**Comment by Slapbox** [comment]
@futtta I think this is a code issue. Across multiple sites I run I've been having this issue when I clear the cache in the plugin (for years across many versions) I'm using it in conjunction with nginx fast-cgi and W3TC, so the issue I'm running into may be one you consider to be outside the scope of this issue tracker, however Autoptimize really improves speeds when used in conjunction with these other solutions so hopefully you might have some thoughts.

**Here's the gist of what seems to be happening:**

1. The cached version of the page from nginx fast-cgi points to a unique URL for the CSS and the JS generated by Autoptimize
2. Clearing Autoptimize and non-Autoptimize caches and then rebuilding the caches leads to the page linking to resources that no longer exist, because Autoptimize has generated new assets at new URLs but somehow everything still points to the old ones even after clearing all caches (including browser.)
3. I deactivate Autoptimize, then clear non-Autoptimize caches, then re-enable Autoptimize, then clear non-Autoptimize caches again
4. Now Autoptimize works with my other caching solutions again

If there's anything I can do to help with troubleshooting this let me know!

**Comment by futtta** [comment]
this 
> Clearing Autoptimize and non-Autoptimize caches and then rebuilding the caches leads to the page linking to resources that no longer exist, because Autoptimize has generated new assets at new URLs but somehow everything still points to the old ones even after clearing all caches (including browser,) which leads to 404s on those linked assets, which of course mangles the entire page.

as links are added by autoptimize after the optimized CSS/ JS has been cached, it is simply impossible for a newly created HTML file to contain links to non-existing optimized CSS/ JS-files. 

logically I see 2 possible explanations;
(a) somehow the HTML is not successfully purged from page cache (W3TC/ nginx/ browser
(b) if first that page cache is cleared and then there are requests coming in while you still have to purge AO cache, then you could have pages in cache that link to CSS/ JS that will disappear as soon as you indeed do purge AO's cache.

hope this helps :)

**Comment by hyperpress** [comment]
The cause of this issue is linked to other caching methods, including some
plugins and some CDNs. It's important in those cases to clear the other
sources of cached pages. That should prevent this.

**Comment by Slapbox** [comment]
@futtta thanks for your response!

Regarding:
> if first that page cache is cleared and then there are requests coming in while you still have to purge AO cache, then you could have pages in cache that link to CSS/ JS that will disappear as soon as you indeed do purge AO's cache.

Even if there are no page requests between clearing the page cache and clearing the AO cache the issue occurs. No matter how many times or what order I clear the caches, I still get this issue.

There's no CDN involved and the other caches are definitely cleared. As best as I can tell AO doesn't create any cached assets just from visiting the Wordpress dashboard pages, so I'm at a loss for an explanation of why clearing both caches before there are any page requests isn't enough.

I'd love to provide a live example of this issue but there's no way to limit the scope of the mangling to just a single page for demonstration purposes unfortunately. Any other thoughts on how I might approach debugging this? Clearing both caches (in a particular order) used to work in the past. I can't say for sure if it's a change in AO, W3TC, or Wordpress itself that caused the behavior to change. Thanks again!

**Comment by hyperpress** [comment]
It's hard to say. Some hosting companies aggressively cache, and there may
be something else going on. I'll keep a lookout and post back if I think of
anything else.

**Comment by futtta** [comment]
Could be related to https://wordpress.org/support/topic/html-minify-v0-9-2/ by @willstocks-tech who has pretty weird issues ever since updating to W3TC 0.9.7.1 or .2, for him rolling back to W3TC 0.9.7.0 is the only way to fix the issue for now.

**Comment by willstocks-tech** [comment]
So, I realised yesterday that for some reason, when I upgraded to to W3TC v0.9.7.2 - W3TC was serving up an old cached version of my page (somewhere around 9th Jan). No matter whether I cleared W3TC caches - nothing updated. Obviously, that was over a month ago and I've had a few content updates since, as well as changes to CSS and JS on my site that would've resulted in new versions of AO scripts/CSS.

I even logged into my hosting (Cloudways) and restarted:
- Apache
- nginx
- Varnish (also purged)
- PHP
- MySQL
- Memcached (also purged)
- Redis (also purged)

I also logged into Cloudflare, disabled performance and purged caches, just in case.

All of these made absolutely no difference. W3TC was still showing the january date as the date of the last "cached"

**Comment by willstocks-tech** [comment]
I've just tried to look at the W3TC diff between 0.9.7 and 0.9.7.1 (I personally wouldn't call it a #.#.#.1 version (based on semver/breaking changes rules) - maybe 0.10 instead??) and the changes are fairly extensive and touch a lot (if not all) of the files within W3TC.
Either way... I got lost/confused after a few lines at which point I gave up! If someone else wants to try to have a look:
https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=2018481%40w3-total-cache&old=1864400%40w3-total-cache&sfp_email=&sfph_mail=

**Comment by Slapbox** [comment]
Great discussion!

I have also tried clearing everything/restarting server services and the server completely, as well as clearing/disabling Cloudflare. Unfortunately I was on 0.9.7 when this began, although I'm on 0.9.7.2 now.

Just to add some additional details about my setup:

- nginx (Cache cleared)
- PHP 7.2
- MariaDB
- Memcached (Cache cleared)

**Comment by willstocks-tech** [comment]
I forgot version numbers - sorry! 
* Debian - 3.16.59-1
* Apache - 2.4.x
* nginx - 1.10.x
* Varnish (also purged) - 4.0.x
* PHP - 7.2.14 (FPM/FastCGI)
* MySQL - 5.7.24
* Memcached (also purged) - 1.4.x
* Redis (also purged) - 4.0
* HTTP/2 - enabled

I purged/cleared the whole lot!
https://support.cloudways.com/which-base-packages-are-deployed-with-cloudways-server/

**Comment by willstocks-tech** [comment]
I've just finished migrating from Cloudways to directly hosting with DigitalOcean - that way I have fine-tuned control and lower-level access to my server config.

I can confirm I am now running:
- Ubuntu 18.04
- Apache 2.4.29 (`mod_disk_cache` disabled as it breaks my site!!! So no Apache level caching!)
- Nginx 1.14.0 (reverse proxy + caching)
- PHP 7.2.15 (FPM via Apache)
  - APCu (W3TC page caching)
- MySQL 5.7.25
- Redis 4.0.9
- HTTP/2 enabled

I will try upgrading W3TC again and will confirm whether the issues I see continue or not. I'm wondering whether Cloudways have some aggressive caching/strange caching at nginx level that results in a W3TC & Autoptimize clash?

**Comment by willstocks-tech** [comment]
OK - Can confirm that the issue no longer appears to exist! I'm now running W3TC 0.9.2 on my DO server (spec above) and everything _appears_ to be working OK!

Therefore, it leads me to believe it's something hosting/config-side, but I'm not sure where to start with regards to helping with that as I had no nginx.conf/apache virtualhost access @ Cloudways - but I'm leaning towards aggressive caching server-side or incompatible caching methods in W3TC being the issue!

I'm inclined to believe this is an issue in one of the two following places:
1) Server - aggressive caching (Varnish, Nginx or Apache)
2) W3TC - Code change that is incompatible with existing server-level caching

I wouldn't be inclined to believe AO is the issue here. I'm more inclined to believe that AO is a "red-herring" with regards to this issue!

**Comment by futtta** [comment]
thanks for the feedback @willstocks-tech :-)
