### ISSUE TITLE
Google fonts not caching for Firefox

### ISSUE THREAD

**Issue by brentlogan** [futtta/autoptimize#240]
Using Version 2.5.0-beta-4, with Autoptimize configured as "Combine and preload in head" there is a brief FOUT in Firefox for the first and all successive page loads. (This doesn't happen in Chrome for this configuration and doesn't happen in Firefox when fonts configured "Leave as is.")

Maybe this is expected behavior and Chrome's behavior is unexpected. 

You can see the behavior on my site at https://brentlogan.com.

**Comment by futtta** [comment]
The reason is not the fact the fonts (or rather; the CSS) is cached, but rather the fact that Firefox does not have native support for `rel="preload"` instead relying on loadCSS which initiates at the onLoad event. Chrome, having preload-support, loads the fonts a lot earlier, preventing visible FOUC.

Until Firefox gets preload-support there is not fix for this I'm afraid. If you need/ want to avoid this behavior you'll have to opt for one of the other Google Fonts optimization options.

hope this clarifies,
frank

**Comment by brentlogan** [comment]
It does, thanks for the response.
