### ISSUE TITLE
Load WebP in supported browsers without the CDN functionality

### ISSUE THREAD

**Issue by Dan0sz** [futtta/autoptimize#241]
I already use Stackpath CDN, but I'd still like to use your WebP functionality (the shortpixel CDN seems to be slower than Stackpath's). That doesn't seem to be possible, since I need to enable the CDN, before the WebP option appears.

Could these options be separated from eachother, or is there are a reason why they're linked?

**Comment by futtta** [comment]
Dag Daan :-)

The reason why they're tight in is because that way I know what the relation between the URL with and without WebP is, which is not the case when trying to support whatever solution.

Given you're in geek-mode already, it's just JS hooking into lazysizes, so it should be easy for you to apply the idea in https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeImages.php#L895-L899 to whatever webp solution you have.

Lastly; Stackpath & Shortpixel _should_ be equally fast, as Shortpixel uses Stackpath for the CDN-part (but off course Shortpixel will also optimize the image before it is cached on CDN) :-)

**Comment by Dan0sz** [comment]
It might have to do with the optimization, making it 'feel' slower. I'll give it another shot then.

Thanks for the explanation. Whenever I get extra geeky, I'll try to implement the WebP functionality into my own CDN. But I'll try out shortpixel again first.
