### ISSUE TITLE
Inline script getting corrupted

### ISSUE THREAD

**Issue by ivanblagdan** [futtta/autoptimize#25]
This inline script is getting corrupted when minified:
`<script type="text/javascript">document.write('<style type="text/css">.tabber{display:none;}<\/style>');</script>`
I've had a issue open with the minification library initially, but it seems it might be a issue in the way its used.
https://github.com/mrclay/minify/issues/483

Any thoughts?

**Comment by futtta** [comment]
Already saw your post there :-)

Anyway; simply add ".tabber" to both CSS & JS optimization exclusion list and all should be well. Alternatively you can wrap the block in noptimize-tags;

`<!-- noptimize --><script type="text/javascript">document.write('<style type="text/css">.tabber{display:none;}<\/style>');</script><!--/ noptimize -->`

frank

**Comment by ivanblagdan** [comment]
Actually we got rid of the thing so its not a issue for myself anymore :D It seemed like a parsing issue that could hit anytime.
If your saying its cool, feel free to close.

**Comment by futtta** [comment]
"cool" would be the wrong word here ;-)

This is actually on my todo-list (cfr. https://wordpress.org/support/topic/inline-css-adds-weird-string-at-the-end-of-the-css)

it is however an edge-case; in that sense that it only happens when;
1. inlined JS is not aggregated (in your case because it has document.write which AO always leaves in place)
AND
2. that inlined JS has a style-tag in it

In that case AO CSS optimization mistakingly sees that style-tags and tries to aggregate it, hence the workaround is needed.

By the way; AO 2.0 will not aggregate inline CSS & JS by default any more (for new installations, at least) to avoid the multitude of problems related to that (inlined CSS loses priority when aggregated, inlined JS often contains page- or request-specific strings that bust AO's cache and cause longer TTFB, ...).

So not closing just yet, but AO 2.0 will solve all of this :-)

**Comment by ivanblagdan** [comment]
Oh great, I'm looking forward to that. Thanks for a great plugin.

**Comment by futtta** [comment]
just commited what I think fixes this issue, would be great if you could test Ivan.

**Comment by futtta** [comment]
considering fixed (based on my own tests) until proven otherwise :-)
