### ISSUE TITLE
CDN - not able to exclude cookies

### ISSUE THREAD

**Issue by BestSolutionNo** [futtta/autoptimize#258]
Hi.

I use AppPresser to access my webpage. When I enable CDN in Autopimize my app is loading only static content. I need to exclude appPressers cookies from been cached. 
Is that possible? 
More info on this page: https://docs.apppresser.com/article/381-caching-issues
Rest of js and css I want to be on CDN.

Thank you for a good product.

best regards Vilfred

**Comment by futtta** [comment]
Hey Vilfred;
First of all, the linked article talks about how page caches should be configured, but AO does not do page caching and does not know about cookies, so that should not be an issue.

Now I have not found any info on Autoptimize or similar plugins, but If you encounter issues, I suggest to try to exclude the apppresser theme (and plugins) from CSS and JS optimization (and optionally untick the "minify excluded CSS/JS"-option. Apparently there also is an ["app preview" which can be used to see if JavaScript errors are thrown on the browser console](https://docs.apppresser.com/article/384-debugging-your-app), that might also help.

If at that point there still are problems, you could try to disable AO based on the URL (specifically `appp=3`) using a couple of lines of code which I can provide.

hope this helps,
frank
