### ISSUE TITLE
multisite option wrapper: blog_id == 1 or is_network_admin?

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#276]
@juanfran-granados; for the options-screen I've switched the `$blog_id === 1` check into `is_network_admin()` because that seems to make more sense (and I don't have to fetch blog_id, call me lazy or correct me if you think I'm wrong).

Now for the autoptimizeOptionsWrapper (I changed the file- and classnames) logic I'm wondering if we could/ should do the same, but (maybe because it's Sunday-morning) I'm less convinced. What's your opinion; leave blog_id check or also switch to `is_network_admin`?

Also; if you have time feel free to go over the changes I committed in [the multisite-test branch](https://github.com/futtta/autoptimize/tree/multisite-test), all feedback is welcomed!

**Comment by juanfran-granados** [comment]
Hello @futtta, I think it's a nice improvement.

Checking the commits, I think it's worth the risk trying to adopt this change also in OptionsWrapper. The only possible issue I can imagine of would be that the function is not declared at that point of execution, as it happened before with is_plugin_active_for_network, that forced me to add the maybe_include_plugin_functions method. But that will be captured in your CI flow, as it was earlier, right?

Once you have that change done, drop me a line and I will test the functionality manually, no problems.

PS: You could avoid checking if current WP installation is a multisite if you check also is_plugin_active_for_network, because that's the first thing it does inside that function.

**Comment by futtta** [comment]
hmmm, doing some manual test now, not OK ... more tomorrow.

**Comment by futtta** [comment]
looking better, as @zytzagoo suggested (via mail) it would be a good idea to add some unit tests to confirm esp. the option-wrapper works correctly. uncharted territory though .. ;-)

**Comment by futtta** [comment]
Man, multisite is crazy! :confused: 

So based on what I see (on error_logging output) the pre_update_option filter is being added but is never called. I thought the reason was that `pre_update_option` as such does not exist, but that [one is supposed to use the option name as part of the filter name](https://developer.wordpress.org/reference/hooks/pre_update_option_option/) (e.g. `pre_update_option_autoptimize_js`), but that doesn't seem to fire `update_autoptimize_option_on_network` either. Might be because of how AO (historically) does not use the settings API and does not have explicit update_option-calls (the form submit implicitly triggers WordPress to update options).

Anyway: the result is (or seems to be) that network options are stored as options of blog with ID 1 and not as real network options?

So; did you ever see `update_autoptimize_option_on_network` being triggerd @juanfran-granados ? Have you been able to set network option that was different from blog 1's setting? And how big (or little) a problem is the fact that network settings = blog 1's settings?

**Comment by juanfran-granados** [comment]
:( Let me check on that, I will write you ASAP.

**Comment by futtta** [comment]
fyi, this is the uncommited code I used to create pre-update filters for each AO option;

```php
        if ( is_plugin_active_for_network( 'autoptimize/autoptimize.php' ) && is_network_admin() ) {
            $_ao_options_array = array('autoptimize_cache_clean', 'autoptimize_cache_nogzip', 'autoptimize_css', 'autoptimize_css_aggregate', 'autoptimize_css_datauris', 'autoptimize_css_justhead', 'autoptimize_css_defer', 'autoptimize_css_defer_inline', 'autoptimize_css_inline', 'autoptimize_css_exclude', 'autoptimize_html', 'autoptimize_html_keepcomments', 'autoptimize_enable_site_config', 'autoptimize_js', 'autoptimize_js_aggregate', 'autoptimize_js_exclude', 'autoptimize_js_forcehead', 'autoptimize_js_justhead', 'autoptimize_js_trycatch', 'autoptimize_version', 'autoptimize_show_adv', 'autoptimize_cdn_url', 'autoptimize_cachesize_notice', 'autoptimize_css_include_inline', 'autoptimize_js_include_inline', 'autoptimize_optimize_logged', 'autoptimize_optimize_checkout', 'autoptimize_extra_settings', 'autoptimize_service_availablity', 'autoptimize_imgopt_provider_stat', 'autoptimize_imgopt_launched', 'autoptimize_imgopt_settings', 'autoptimize_minify_excluded');
            foreach ( $_ao_options_array as $_ao_option_name ) {
                add_filter( 'pre_update_option_'.$_ao_option_name, array( $this, 'update_autoptimize_option_on_network' ), 10, 3 );
            }
        }
```

**Comment by juanfran-granados** [comment]
I haven't been able to check the code, but that shouldn't be the problem. If you check the [wp-includes/options.php](https://core.trac.wordpress.org/browser/tags/5.2.3/src/wp-includes/option.php#L332) code, you will encounter this filter, right after the one you said. I prefered to use this one to not hardcode all options name in an array.

https://developer.wordpress.org/reference/hooks/pre_update_option/

At the moment I did the development, I debugged the code and the filter was effective. Let me check again, please.

**Comment by futtta** [comment]
ah, that indeed makes things a lot simpler, must have missed that!

**Comment by juanfran-granados** [comment]
Hello @futtta,

I've noticed that there was a javascript error (unslider not defined). The problem is that autoptimize_admin_scripts function was not being called in network admin, due to the hook in network is admin_print_scripts-admin_page_autoptimize and AO expects it to be admin_print_scripts-settings_page_autoptimize. I really don't know why I did not see this before in the tests, because it just stops you from configuring the plugin.

Moving forward from the mistery, if you read the codex for [admin_print_scripts](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_print_scripts) it says:

> admin_print_scripts mainly used to echo inline javascript in admin pages header. admin_print_scripts should not be used to enqueue styles or scripts on the admin pages. Use admin_enqueue_scripts instead.

So I changed that in this [commit](https://github.com/mirai-wordpress/autoptimize/commit/9d806b92003ff5fd5e0f6cb2731b5ec7eb997b47), to make it work as expected. I've also tested the main functionality:
* Configure in network and test that a site use this settings.
* Configure in site and test that a site use this settings.

Please, check this and tell me if you can at least test multisite.

Thanks!

**Comment by futtta** [comment]
The unslider stuff was already fixed in one of my commits, saving options
did work, only issue was that it saved to blog_1 options instead of to the
network options? Did you try the multisite-test branch with my commits?

**Comment by futtta** [comment]
OK, was able to advance a bit; adding action `check_multisite_on_saving_options` to `init` in the optionsWrapper does not work because the optionswrapper itself is called later (at part of `setup` at `plugins_loaded`). making `check_multisite_on_saving_options` public static and (conditionally) calling that from aoMain's `add_hooks` works.

Next problem `is_network_admin` always returns false, so that cannot be used. The problem very likely is due to the fact that form submit is to `wp-admin/options.php` and only after that one is redirected to the network-URL (which I found out when trying to implement a workaround by comparing current URL with the network admin url). No workaround for this one yet ... :-/

**Comment by futtta** [comment]
New status; it works, but I feel like it is an ugly hack :)

* problem indeed was what I [described in 2nd paragraph here](https://github.com/futtta/autoptimize/issues/276#issuecomment-536567259)
* current solution: comparing the referring URL (added as hidden form element by WordPress core) with what should be the network settings URL and if so consider a post from the network settings page (see https://github.com/futtta/autoptimize/blob/multisite-test/classes/autoptimizeOptionWrapper.php#L98-L115)
* a better way would be to change the main form action to point to the network settings URL on the network settings page, like this;

```php
<?php
if ( is_network_admin() ) {
    $_form_action    = network_admin_url( 'settings.php' );
} else {
    $_form_action    = admin_url( 'options.php' );
}
?>
<form method="post" action="<?php echo $_form_action; ?>">
<?php settings_fields( 'autoptimize' ); ?>
```

But the problem is that for reasons I'm not smart enough to understand the nonce-check fails on the network admin-page. So what do you guys (@juanfran-granados & @zytzagoo ) think? The latter solution would be a lot cleaner as we could (probably) simply use is_network_admin() for that, but then we need the nonce to be valid, any ideas?

**Comment by futtta** [comment]
Forgetting about that ugly workaround from above, I think the multisite-stuff is more or less ready now with the last couple of commits (including 2 tests for multisite options being either site- or network-based that depend an a constant to mimic AO being network-enabled which is also a hackish workaround).

@juanfran-granados can you download (pull) the latest version of [the multisite-test branch](https://github.com/futtta/autoptimize/tree/multisite-test) and test thoroughly? if you give the green light I'll merge with beta for (hopefully) wider testing.

**Comment by futtta** [comment]
so @juanfran-granados have you had a chance to test the multisite-test branch already? :-)

**Comment by juanfran-granados** [comment]
Hello @futtta, sorry for the delay, we've been busy releasing our new stack.

I start checking your comments and branch right now, I'll let you know.

**Comment by juanfran-granados** [comment]
I've checked your code.

From a functional point of view, it works as expected:
- If AO settings per site is checked, in site settings are used.
- If AO settings per site is not checked, site settings shows a message and network settings are used.

So far, so good :+1: 

About the problem described in the second paragraph of the [previous comment](https://github.com/futtta/autoptimize/issues/276#issuecomment-536567259):

> Next problem is_network_admin always returns false, so that cannot be used. The problem very likely is due to the fact that form submit is to wp-admin/options.php and only after that one is redirected to the network-URL (which I found out when trying to implement a workaround by comparing current URL with the network admin url). No workaround for this one yet ... :-/


I've checked your second solution in my local environment. It does not work, as you said, because the nonce check is network admin settings.php checks that the action of the nonce must be siteoptions, and you have autoptimize-options, set by the Settings API that you use.

Anyway, that's what I covered using the pre_update_option hook in AutoptimizeOption class.

**Comment by futtta** [comment]
So you consider this ready for testing by a larger audience @juanfran-granados ?

**Comment by juanfran-granados** [comment]
Yes, let's go for it.

**Comment by futtta** [comment]
merged in the beta-branch :-)
