### ISSUE TITLE
add to cart error

### ISSUE THREAD

**Issue by szdenes** [futtta/autoptimize#286]
Hi,

In some cases, the add to cart process doesn't ends. It's just rendering and rendering. Please check the video, and give me a feedback if it's an autooptimize issue or not. 

thanks,
Szilard
video: https://a.uguu.se/By0aBaMdOUW6.mp4
ref link: https://www.catyourday.com/home/shop/cat-care/cat-litter-trapping-mat/

**Comment by futtta** [comment]
After clicking "add to cart" the response is a redirect to the cart in HTTP instead of HTTPS, which is blocked by the browser (see the "blocked/ mixed content" status in the last shot in your video), so very unlikely to be due to AO.

(next time please post your question in the AO forum, I use Github for development purpose/ code issues)

**Comment by szdenes** [comment]
Ok, thanks for the quick answer, I'll look after that issue! Please delete the question from here.
