### ISSUE TITLE
ErrorDocument 404 not being written to .htaccess for fallback

### ISSUE THREAD

**Issue by mkornatz** [futtta/autoptimize#304]
I have added the following to my theme's `functions.php`:

```
add_filter( 'autoptimize_filter_cache_do_fallback', '__return_true');
```

I also have removed the generated `.htaccess` file at  `wp-content/cache/autoptimize/.htaccess`. However, when the `.htaccess` file is automatically re-generated, it is missing the `ErrorDocument 404` line, which is preventing the fallback from working.

My question is, where is the proper place to add this filter? Is adding it in the theme functions.php not correct?

**Comment by futtta** [comment]
can you check if `wp-content/cache/js/autoptimize_fallback.js` and `wp-content/cache/css/autoptimize_fallback.css` exist?

if not (which will probably be the case), then the code snippet is not active somehow. the theme functions.php _should_ work, but maybe -due to other code there- it is not read/ executed. try adding it higher up in the file or use <a href="https://wordpress.org/plugins/code-snippets/">the code snippets plugin</a> (which I prefer for a multitude of reasons ;-) ).

**Comment by mkornatz** [comment]
Yep, those files both exist and are properly being generated.

When I updated the line at https://github.com/futtta/autoptimize/blob/beta/classes/autoptimizeCache.php#L592 to read `if ( true || self::do_fallback() ) {` then everything works as expected. So, `self::do_fallback()` is returning `false` there, but `true` when generating the cache.

My first thought was that the `cacheavail()` function is being executed prior to the theme's function.php file being required (where the filter is being added).

**Comment by futtta** [comment]
I assume you're using 2.6.1, can you download the beta from here instead?
That particular problem (which indeed is a question of hooks & priority)
should be fixed there.

**Comment by mkornatz** [comment]
Ah ok, yep I'm on 2.6.1. That makes sense. I'll do just that. Thank you for your help!
