### ISSUE TITLE
Cron event problem

### ISSUE THREAD

**Issue by boywithk9** [futtta/autoptimize#312]
I'm using the Autoptimize 2.7 beta, and I'm having a problem with CriticalCSS. There's no ao_ccss_queue event in Tools > Cron Events. But since it's no longer possible to deactivate the CriticalCSS extension as suggested in the troubleshooting doc for the live version, I'm not able to get it back. Also, in the job queue, all the rows are stuck on New (presumably related to the cron issue). Also, on the cron events page, there's a notice: The DISABLE_WP_CRON constant is set to true. WP-Cron spawning is disabled.

**Comment by futtta** [comment]
OK, can you;
1. try disabling/ re-enabling Autoptimize to see if the cron-job is added?
2. assuming you have wp crontrol installed, try adding ao_ccss_queue as a
new cron job (tools -> cron event -> scroll down -> add cron event -> hook
name is ao_ccss_queue, recurrence is 10 minutes)
3. re. disable_wp_cron; i assume that is added at host level and it
_should_ indicate an OS-level cron is used instead of wordpress cron.

**Comment by futtta** [comment]
(2) did the trick.
