### ISSUE TITLE
toolbar clear cache timeout

### ISSUE THREAD

**Issue by futtta** [futtta/autoptimize#54]
@pablocusto ; [a tester had a problem with the ajax request not getting a response](https://wordpress.org/support/topic/preparing-for-autoptimize-210-wanna-test?replies=8#post-8709332) when clearing the cache from the toolbar. could we add a timeout of e.g. 5s in the static toolbar JS & handle that gracefully somehow?

**Comment by pablocusto** [comment]
Mmm .. let me see if Ajax call does not have a callback for such situations.

If not, I'll see how to do it with a timeout function that can be canceled
in the situation that there is a satisfactory response, since in the case
of a timeout, we should not reset the data reports of the AO admin bar.

2016-08-02 15:34 GMT-03:00 frank goossens <notifications@github.com>:

**Comment by futtta** [comment]
this seems the relevant SO answer; http://stackoverflow.com/a/5225624/237449 ;-)

**Comment by pablocusto** [comment]
Nice! Excelent!!

So basically it would be something like this:

jQuery.ajax({
> type : 'GET',
> url : autoptimize_ajax_object.ajaxurl,
> data : {'action':action, 'nonce':autoptimize_ajax_object.nonce},
> dataType: 'json',
> cache : false,
> timeout : 5000,
> success : function( data )
> {
> // Remove the Autoptimize Loading Modal
> modal_loading.remove();
> // Reset output values & class names of cache info
> jQuery( '#wp-admin-bar-autoptimize-cache-info .size' ).attr( 'class',
> 'size green' ).html( '0.00 B' );
> jQuery( '#wp-admin-bar-autoptimize-cache-info .files' ).html( '0' );
> jQuery( '#wp-admin-bar-autoptimize-cache-info .percentage .numbers'
> ).attr( 'class', 'numbers green' ).html( '0%' );
> jQuery( '#wp-admin-bar-autoptimize-cache-info .autoptimize-radial-bar
> .fill' ).attr( 'class', 'fill bg-green' );
> // Reset the class names of bullet icon
> jQuery( '#wp-admin-bar-autoptimize' ).attr( 'class', 'menupop
> bullet-green' );
> // Reset the Radial Bar progress
> jQuery( '#wp-admin-bar-autoptimize-cache-info .autoptimize-radial-bar
> .mask.full, #wp-admin-bar-autoptimize-cache-info .autoptimize-radial-bar
> .fill' ).css({
> '-webkit-transform' : 'rotate(0deg)',
> '-ms-transform' : 'rotate(0deg)',
> 'transform' : 'rotate(0deg)'
> });
> },
> error: function( jqXHR, textStatus )
> {
> if ( textStatus === 'timeout' )
> {
> // Remove the Autoptimize Loading Modal
> modal_loading.remove();
> }
> }
> });



Now, we must think how to report that cleaning was not performed
successfully because of a timeout.

You have something in mind of how you want us to make this report?

Some nice Popup, modify the loading icon by another representative, or with
a simple javascript alert?


2016-08-02 17:49 GMT-03:00 frank goossens <notifications@github.com>:

**Comment by futtta** [comment]
Let's try to insert a div with class "notice notice-error" underneath the first .wrap > h1, saying something like "Your Autoptimize cache might not have been purged successfully, please check on the Autoptimize settings-page." (string to go in autoptimizeToolbar.php in wp_localized_script).

**Comment by futtta** [comment]
fixed with https://github.com/futtta/autoptimize/pull/56
