### ISSUE TITLE
Separate head and body scripts

### ISSUE THREAD

**Issue by szepeviktor** [futtta/autoptimize#57]
Is there an option to have aggregated head scripts and aggregated body scripts separately?

**Comment by futtta** [comment]
no, there is not (yet).

**Comment by pbowyer** [comment]
Thanks for your work on Autoptimize. I switched to it last month; previously I was using BWP-Minify, which had highly variable load times and broke Google's "This Site is Mobile Friendly" check.

Due to legacy code the site I'm working on needs some JavaScript in the `<head>`, so I used WordPress's `wp_enqueue_script` to assign some scripts to the head and the majority to the footer. BWP Minify compressed these where they were, and I ended up with two minified JS files.

I understand why Autoptimize scans the HTML vs hooks into the WordPress functions. I thought property `$domovelast` would let me specify which files to put in `<body>` when _"Force JavaScript in &lt;head>?"_ is checked, but that's not its purpose.

Are you open to a patch that would add this functionality? I envisage another setting called _"Preserve head/body location of JavaScript"_, and then changing the parsing and extraction to treat the `<head>` and `<body>` separately, and then merge back together or not depending on the setting.

If there's a better way to handle this, or it is already present, it'd be great to hear.

**Comment by futtta** [comment]
Welcome @pbowyer :-)

Best way to do this without having to code would be _not_ to force JS in head, but to exclude the JS you want to stay in head (which I assume/ hope is a short list). you could then use the new `autoptimize_filter_js_minify_excluded` filter in the upcoming AO2.2 to minify the JS in head?

But if you were to code and you would do a PR, I would most certainly consider off course :-)
