### ISSUE TITLE
Allow to put inline CSS after HTML

### ISSUE THREAD

**Issue by alexmoreno** [futtta/autoptimize#64]
This is a easy way to fix "prioritize visible content", I guess, instead of all the work of critical CSS. I'm having problems messing on a site made by thirds where I can't upgrade my PageSpeed score due to the huge chunk of CSS generated and put after HTML, or (I'm not sure) some problem with PageSpeed's parse and "CSS inline and defer".
What do you think?

**Comment by futtta** [comment]
> What do you think?

I <s>think</s> know you can do that already by selecting the "inline all CSS" option and this simple filter;
```php
add_filter('autoptimize_filter_css_replacetag','alexm_css_replacetag',10,1);
function alexm_css_replacetag($replacetag) {
	return array("</body>","before");
	}
```

But I doubt this will really help improve your pagespeed score; the entire HTML, including the inilned CSS at the bottom, would have to be read to be able to render the page. Due to the fact that the CSS goes last, there would probably even be more round-trip times.

I could be mistaking off course, do give that filter a try (be sure to tick the "inline all CSS"-option).

**Comment by alexmoreno** [comment]
You're right. it actually made my PageSpeed's score _worse_. hahaha
What do you suggest then?
Thanks :)

**Comment by futtta** [comment]
above the fold/ critical css is the only way really.
