### ISSUE TITLE
nginx .gz vs .gzip

### ISSUE THREAD

**Issue by raciasolvo** [futtta/autoptimize#66]
> The ngx_http_gzip_static_module module allows sending precompressed files with the “.gz” filename extension instead of regular files.

[http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html](http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html)

I use
`add_filter('autoptimize_filter_cache_create_static_gzip', '__return_true');`
and have .gzip now.
Is it possible to change the plugin, so it creates the .gz?

**Comment by futtta** [comment]
this [was already brought up here](https://github.com/futtta/autoptimize/issues/59) and fixed with [this pull request](https://github.com/futtta/autoptimize/commit/7f9b683b4f88187e9e96217de33b4a45c5fb96f6). you could edit as in the pull request, or you could download the current dev-version of AO from https://github.com/futtta/autoptimize/archive/master.zip to get that fix :-)
