### ISSUE TITLE
log alerts for unreadable CSS

### ISSUE THREAD

**Issue by drzraf** [futtta/autoptimize#78]
When developing an asset may be unavailable.
If autoptimize is off, a 404 is triggered that helps spotting the problem.
But is autoptimize is on, CSS content is simply dropped which lead to a partial compressed CSS without notification. This could be misleading.

**Comment by futtta** [comment]
errr .... well, I think the problem you're referring to exists in the current version (2.1.0) but is effectively fixed with [this commit](https://github.com/futtta/autoptimize/commit/1386e4fe1d390d7c099cab29668bf2f75798fab6#diff-9c29111cb6aef898aaad0eadb9bc95c0R111) which has [AO bail from aggregating the file if it cannot be found/ read](https://github.com/futtta/autoptimize/blob/master/classes/autoptimizeBase.php#L106-L111)?

**Comment by drzraf** [comment]
It's not aggregated, but is there any somehow a trace of this in a log so that the issue can be seen and fixed?

**Comment by futtta** [comment]
no, AO doesn't do any error-logging (yet, it may in the future although the question of what to log when is not an easy one, logs could quickly become _very_ large), but as without AO this change ensures that;

> a 404 is triggered that helps spotting the problem

:-)

**Comment by futtta** [comment]
closing as fixed on DEV-version.
